### ISSUE TITLE
I'm not able to install the package but I followed the instructions...

### ISSUE THREAD

**Issue by TaniaMigliorini** [advicepharma/laravel-tablegenerator#8]
I tried to open your package laravel-table generator on a new laravel project, but I've found some issues....Can you help me?
![Screenshot (5)](https://user-images.githubusercontent.com/101468501/162477900-68e960ce-1af6-4d44-9225-b7dc62a91069.png)

**Comment by giagara** [comment]
Laravel 9 is now compatible. See PR https://github.com/advicepharma/laravel-tablegenerator/pull/9#issue-1203074687
